#ifndef GAME_SETTINGS_DEFINED
#define GAME_SETTINGS_DEFINED

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define BLOCK_SIZE 180

#define UI_WIDTH 400
#define TEXT_HEIGHT 18
#define UI_PADDING 8
#define X_PADDING -0.30
#define Y_PADDING -0.90
#define MAX_WORLD_ENTITIES 512
#define HISTORY_STEPS 128
#define ANIMATION_SINGLE_STEP_TIME 0.25

#endif
